{ config, pkgs, waysip, unstable-small, ... }: {
  home-manager.users.${config.user}.home.packages = with pkgs; [
    abiword
    calibre
    ff2mpv-rust
    freerdp
    gnumeric
    grim
    hyprpicker
    iptables-nftables-compat
    krita
    magic-wormhole-rs
    meld
    nftables
    pam_u2f
    pavucontrol
    pinentry-gnome3
    playerctl
    pulseaudio
    push2talk
    qalculate-gtk
    signal-desktop
    sipcalc
    sleek-todo
    slurp
    swaybg
    swaylock
    swayr
    systembus-notify
    tailspin
    trash-cli
    udiskie
    unstable-small.ttl
    usbguard
    vault-bin
    vimiv-qt
    waysip
    wev
    wf-recorder
    wldash
    zathura
  ];
}
